### ISSUE TITLE
main.py file is missing

### ISSUE THREAD

**Issue by ajinkya933** [amineHY/docker-streamlit-app#1]
main.py file is missing on your repo. I tried adding main.py:
```
import streamlit as st
st.write("hello")
```

and then ran your repo:
docker run -ti --rm <dockerImagename> streamlit run main.py

I get :

```
  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://117.99.99.109:8501
```

but when I click on these url the hello text dosent appear. Any pointers on why this happens ?

**Comment by amineHY** [comment]
Hi @ajinkya933,

have you tried to mention the docker image ? **aminehy/docker-streamlit-app:latest**

here is the command that worked:
`docker run -ti --rm aminehy/docker-streamlit-app:latest streamlit run main.py`

Check out the official documentation of `docker run` here: https://docs.docker.com/engine/reference/commandline/run/

**Comment by ajinkya933** [comment]
I did:

```
docker pull aminehy/docker-streamlit-app:latest
```

and then I ran:
```
docker run -ti --rm aminehy/docker-streamlit-app:latest streamlit run main.py
```

for this I get error: 
```
Error: Invalid value: File does not exist: main.py
```

I did ssh into your container and here's the data:
```
$ docker run -it aminehy/docker-streamlit-app /bin/bash
root@5227acb4f92a:/app# ls
Dockerfile  LICENSE  README.md
```

I did not find the file main.py. Where is its location ?

**Comment by amineHY** [comment]
Sorry here is the correct command, i have tried it with your `main.py` file
`docker run -ti --rm -v $(pwd):/app aminehy/docker-streamlit-app:latest streamlit run main.py`

`-v $(pwd):/app`  attach your current application folder to the docker container

**Comment by ajinkya933** [comment]
```
(base) ajinkya@ajinkya-AB350-Gaming-3:~/Documents/ajinkya_streamlit$ ls
main.py
(base) ajinkya@ajinkya-AB350-Gaming-3:~/Documents/ajinkya_streamlit$ pwd
/home/ajinkya/Documents/ajinkya_streamlit
(base) ajinkya@ajinkya-AB350-Gaming-3:~/Documents/ajinkya_streamlit$ sudo docker run -ti --rm -v /home/ajinkya/Documents/ajinkya_streamlit:/app aminehy/docker-streamlit-app:latest streamlit run main.py

  For better performance, install the Watchdog module:
  
  $ pip install watchdog

        

  A new version of Streamlit is available.

  See what's new at https://discuss.streamlit.io/c/announcements

  Enter the following command to upgrade:
  $ pip install streamlit --upgrade


  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://117.99.99.109:8501
```

I tried now I do get network and external url but the problem is both the urls wont produce any output on web browser. The web browser (chrome) screen keeps on loading when I open these url but nothing shows up in the end.

I also tried through: http://localhost:8501 but no luck

**Comment by amineHY** [comment]
It weird, to me, as soon as your application is launched, this means that it is running very file inside the docker container. I wich I can get more information about your problem to help you.

**Comment by amineHY** [comment]
I juste updated the docker image and aded the missing `main.py`
Hopefully this time it will work for you @ajinkya933
